Wait for the database to be ready before trying to db:create/migrate

diff --git a/docker-assets/entrypoint b/docker-assets/entrypoint
--- a/docker-assets/entrypoint
+++ b/docker-assets/entrypoint
@@ -3,6 +3,23 @@
 export RAILS_ENV=production
 export DATABASE_URL="postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME?encoding=utf8&pool=5&wait_timeout=5"
 
+function check_svc_status() {
+  local SVC_NAME=$1 SVC_PORT=$2
+
+  [[ $# -lt 2 ]] && echo "Error something seems wrong, we need at least two parameters to check service status" && exit 1
+
+  echo "== Checking ${SVC_NAME}:$SVC_PORT status =="
+
+  while true; do
+    ncat ${SVC_NAME} ${SVC_PORT} < /dev/null && break
+    sleep 5
+  done
+  echo "${SVC_NAME}:${SVC_PORT} - accepting connections"
+}
+
+# Wait for postgres to be ready
+check_svc_status $DATABASE_HOST $DATABASE_PORT
+
 # TODO: REMOVE THIS -> Move to Operator?
 bundle exec rake db:create db:migrate
 
